// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47KhR2-g_DBavOctNqztwL2VbKf9xWng',
    appId: '1:491093025697:web:5bd0b6a7abae93487961e0',
    messagingSenderId: '491093025697',
    projectId: 'toy-manager',
    authDomain: 'toy-manager.firebaseapp.com',
    storageBucket: 'toy-manager.firebasestorage.app',
    measurementId: 'G-JQC6JPQDV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9q-Gk0Pwws0pFXHwdDZiT4aLLBbCGmoc',
    appId: '1:491093025697:android:45e5db29d53a12697961e0',
    messagingSenderId: '491093025697',
    projectId: 'toy-manager',
    storageBucket: 'toy-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsRorpyClHeVAYHiI_Vdu4a_Rf3kARuQ4',
    appId: '1:491093025697:ios:499d095e1bba88657961e0',
    messagingSenderId: '491093025697',
    projectId: 'toy-manager',
    storageBucket: 'toy-manager.firebasestorage.app',
    iosBundleId: 'com.example.toyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47KhR2-g_DBavOctNqztwL2VbKf9xWng',
    appId: '1:491093025697:web:a0fdc66615e68ff57961e0',
    messagingSenderId: '491093025697',
    projectId: 'toy-manager',
    authDomain: 'toy-manager.firebaseapp.com',
    storageBucket: 'toy-manager.firebasestorage.app',
    measurementId: 'G-MV2JM8YX1E',
  );
}
